r2013-02-18-tunr/config/routes.rb
R20130218Tunr::Application.routes.draw do
  root :to => 'home#index'

  resources :users, :except => [:edit] do
    collection do
      get 'edit'
    end
  end

  resources :songs do
    member do
      get 'cart'
      post 'purchase'
      post 'refund'
    end
  end

  resources :albums do
    member do
      post 'purchase'
    end
  end

  resources :genres, :artists, :mixtapes

  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'
end

r2013-02-18-tunr/app/models/song.rb
# == Schema Information
#
# Table name: songs
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  image      :string(255)
#  filename   :string(255)
#  album_id   :integer
#  artist_id  :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  cost       :decimal(, )
#

class Song < ActiveRecord::Base
  attr_accessible :name, :image, :filename, :cost, :genre_ids
  belongs_to :album, :inverse_of => :songs
  belongs_to :artist, :inverse_of => :songs
  has_and_belongs_to_many :mixtapes
  has_and_belongs_to_many :genres
  validates :name, :filename, :presence => true
  validates :cost, :numericality => {:greater_than_or_equal_to => 0}
end

r2013-02-18-tunr/app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_filter :check_if_admin, :only => [:new, :create, :edit, :update]
  before_filter :check_if_user, :only => [:cart, :purchase, :refund]

  def index
    @songs = Song.order(:name)
  end
  def show
    @song = Song.find(params[:id])
  end
  def cart
    @song = Song.find(params[:id])
  end
  def refund
    song = Song.find(params[:id])
    if song.in?(@auth.mixtape_songs)
      @auth.balance += (song.cost * 0.70)
      @auth.save
      @auth.mixtapes.each do |mix|
        mix.songs.delete(song)
      end
    end
    redirect_to(root_path)
  end
  def purchase
    song = Song.find(params[:id])
    if song.cost <= @auth.balance
      @auth.balance -= song.cost
      @auth.save
      params[:song][:mixtape_ids].each do |mix_id|
        mixtape = Mixtape.find(mix_id)
        mixtape.songs << song
      end
    end
    redirect_to(root_path)
  end
  def new
    @song = Song.new
  end
  def create
    @song = Song.new(params[:song])
    if @song.save
      redirect_to(songs_path)
    else
      render :new
    end
  end
  def edit
    @song = Song.find(params[:id])
    render :new
  end
  def update
    @song = Song.find(params[:id])
    if @song.update_attributes(params[:song])
      redirect_to(songs_path)
    else
      render :new
    end
  end
end

r2013-02-18-tunr/app/views/songs/cart.html.haml
.row
  .five.columns
    = render(:partial => 'shared/errors', :locals => {:object => @song})
    = form_for @song, :url => purchase_song_path(@song), :method => 'post' do |f|
      = f.label :name
      = f.text_field :name, :disabled => true
      = f.label :cost
      = f.text_field :cost, :disabled => true
      %p
        - @auth.mixtapes.order(:name).each do |mixtape|
          %span= mixtape.name
          = check_box_tag 'song[mixtape_ids][]', mixtape.id
      = f.submit 'Purchase Song', :class => 'button radius'
  .seven.columns

r2013-02-18-tunr/app/views/songs/index.html.haml
%p.newlink= link_to('New Song', new_song_path, :class => 'button radius') if is_admin?
= render :partial => '/shared/songs', :locals => {:songs => @songs}

r2013-02-18-tunr/app/views/songs/new.html.haml
.row
  .five.columns
    = render(:partial => 'shared/errors', :locals => {:object => @song})
    = form_for @song do |f|
      = f.label :name
      = f.text_field :name, :autofocus => true
      = f.label :image
      = f.text_field :image
      = f.label :filename
      = f.text_field :filename
      = f.label :cost
      = f.text_field :cost
      %p
        - Genre.find(:all, :order => 'LOWER(name)').each do |genre|
          %span= genre.name
          = check_box_tag 'song[genre_ids][]', genre.id, genre.in?(@song.genres.to_a)
      = f.submit nil, :class => 'button radius'
  .seven.columns

r2013-02-18-tunr/app/views/songs/show.html.haml
%h1= @song.name
= render :partial => '/shared/songs', :locals => {:songs => [@song]}